
name: Build and Test
on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: ci/docker-run.sh ci/build.sh --ci Release

  build-debug:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v4
      - name: Build Debug
        run: ci/docker-run.sh ci/build.sh --ci Debug
          #- name: save build artifacts
          #  uses: actions/upload-artifact@v3
          #  with:
          #    name: debug-build
          #    path: build/Debug/dist

  unit-test-release:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-release]
    steps:
      - uses: actions/checkout@v4
      - name: Unit Tesst (Release)
        run: ci/docker-run.sh ci/run_utest.sh Release

  unit-test-debug:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Unit Tesst (Debug)
        run: ci/docker-run.sh ci/run_utest.sh Debug

  smoke-test-release:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-release]
    steps:
      - uses: actions/checkout@v4
      - name: Run Smoke-Tests
        run: ci/docker-run.sh ci/run_smoketests.sh Release

  smoke-test-debug:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Run Smoke-Tests
        run: ci/docker-run.sh ci/run_smoketests.sh Debug
 
  code-lint:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-release]
    steps:
      - uses: actions/checkout@v4
      - name: Check Licence
        run:  ci/docker-run.sh ci/checklicense.sh
      - name: Lint Code
        run: ci/docker-run.sh ci/code_lint.py --ci
