
name: Build and Test
on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: ci/docker-run.sh ci/build.sh --ci Release
      - name: save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: build/Release/dist

  build-debug:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v4
      - name: docker pwd
        run: ci/docker-run.sh pwd
      - name: docker ls
        run: ci/docker-run.sh ls -la
      - name: docker env
        run: ci/docker-run.sh env
      - name: pwd
        run: pwd
      - name: ls
        run: ls -la
      - name: env
        run: env
      - name: build docker container
        uses: docker/build-push-action@v2
        with:
          tags: elos-build:latest
          push: false
          file: ci/Dockerfile
      - name: Build Debug Docker
        uses: addnab/docker-run-action@v3
        with:
          image: elos-build:latest
          options: --rm -v ${{ github.workspace }}:/build/elos -w /base/elos
          run: ci/build.sh --ci Debug
      - name: Build Debug
        run: ci/docker-run.sh ci/build.sh --ci Debug
      - name: save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-build
          path: build/Debug/dist

  unit-test-release:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-release]
    steps:
      - uses: actions/checkout@v4
      - name: Unit Tesst (Release)
        run: ci/docker-run.sh ci/run_utest.sh Release
      - name: save test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-release-results
          path: build/Release/result/unit_tests

  unit-test-debug:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Unit Tesst (Debug)
        run: ci/docker-run.sh ci/run_utest.sh Debug
      - name: save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-debug-results
          path: build/Debug/result/unit_tests

  smoke-test-release:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-release]
    steps:
      - uses: actions/checkout@v4
      - name: Run Smoke-Tests
        run: ci/docker-run.sh ci/run_smoketests.sh Release
      - name: save test results
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-release-results
          path: build/Release/result/smoketests_results

  smoke-test-debug:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Run Smoke-Tests
        run: ci/docker-run.sh ci/run_smoketests.sh Debug
      - name: save test results
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-debug-results
          path: build/Debug/smoketests_results

  code-lint:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    needs: [build-release]
    steps:
      - uses: actions/checkout@v4
      - name: Check Licence
        run:  ci/docker-run.sh ci/checklicense.sh
      - name: Lint Code
        run: ci/docker-run.sh ci/code_lint.py --ci
      - name: save lint results
        uses: actions/upload-artifact@v3
        with:
          name: code-lint-results
          path: build/Release/cmake/lint_results
